
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';
import { id, SocialLinkHistoryDto } from '@ottery/ottery-dto';

export type SocialLinkDocument = SocialLink & Document;

@Schema()
export class SocialLink {
  /**
   * the id that is generated by mongo
   */
  _id: id;

  @Prop({required:true})
  users: id[]; //this should only be two users

  @Prop({required:true})
  history: SocialLinkHistoryDto[];
}

export const SocialLinkSchema = SchemaFactory.createForClass(SocialLink);
