
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';
import { SocialLinkHistoryDto, id } from '@ottery/ottery-dto';

export type ImageFileDocument = ImageFile & Document;

@Schema()
export class ImageFile {
  /**
   * the id that is generated by mongo
   */
  _id: id;

  @Prop({required:true})
  url: string; //this should only be two users

  @Prop({required:true})
  key: string;
}

export const ImageFileSchema = SchemaFactory.createForClass(ImageFile);
